# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: snippy-ng
  version: "0.0.1"

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - python -m pip install . -v

requirements:
  host:
    - python >=3.11
    - pip
    - hatchling
  run:
    - python >=3.11
    - click
    - packaging
    - pydantic
    - biopython
    - numpy
    - scikit-learn >=1.7

tests:
  - python:
      imports:
        - snippy_ng
