from pathlib import Path
from typing import Optional

from Bio import Phylo, SeqIO
from pydantic import Field
from snippy_ng.stages import BaseOutput, BaseStage
from snippy_ng.dependencies import biopython, iqtree
from snippy_ng.exceptions import StageExecutionError
from snippy_ng.constants import NEWICK_BRANCH_LENGTH_FORMAT


class TreeBuildingError(StageExecutionError):
    """Custom exception for errors during tree building stage execution."""
    pass


class IQTreeBuildTreeOutput(BaseOutput):
    bionj: Path = Field(..., description="BIONJ starting tree generated by IQ-TREE")
    checkpoint: Path = Field(..., description="IQ-TREE checkpoint file for run resumption")
    contree: Optional[Path] = Field(None, description="Consensus tree from bootstrap replicates (not produced in fast mode)")
    iqtree: Path = Field(..., description="IQ-TREE run summary file with model and fit statistics")
    log: Path = Field(..., description="IQ-TREE execution log file")
    mldist: Path = Field(..., description="Pairwise ML distance matrix produced by IQ-TREE")
    splits: Optional[Path] = Field(None, description="Split support file in NEXUS format (not produced in fast mode)")
    tree: Path = Field(..., description="Output tree file in Newick format")


class ScaleTreeToSNPsOutput(BaseOutput):
    tree: Path = Field(..., description="Tree with branch lengths scaled to expected SNP counts")


class IQTreeBuildTree(BaseStage):
    """
    Filter a multiple sequence alignment to retain only positions present
    in a specified fraction of samples (soft core).
    """

    aln: Path = Field(..., description="Input multiple sequence alignment file in FASTA format")
    model: str = Field(default="GTR+G", description="Substitution model for IQ-TREE")
    bootstrap: int = Field(default=1000, description="Number of ultrafast bootstrap replicates to perform")
    fconst: Optional[str] = Field(default=None, description="Constant patterns to add into alignment in format a,c,g,t (e.g. 10,5,0,0)")
    fast_mode: bool = Field(default=False, description="Use fast mode for rough tree search (faster but less accurate)")

    _dependencies = [iqtree]

    @property
    def output(self) -> IQTreeBuildTreeOutput:
        prefix = Path(self.prefix)
        contree = None
        splits = None
        if not self.fast_mode:
            contree=prefix.with_suffix(".contree")
            splits=prefix.with_suffix(".splits.nex")

        return IQTreeBuildTreeOutput(
            bionj=prefix.with_suffix(".bionj"),
            checkpoint=prefix.with_suffix(".ckp.gz"),
            contree=contree,
            iqtree=prefix.with_suffix(".iqtree"),
            log=prefix.with_suffix(".log"),
            mldist=prefix.with_suffix(".mldist"),
            splits=splits,
            tree=prefix.with_suffix(".treefile"),
        )

    def create_commands(self, ctx):
        validate_aln_cmd = self.python_cmd(
            self.check_aln_has_three_samples,
            description="Validating that the input alignment contains at least 3 samples"
        )
        iqtree_cmd = self.shell_cmd(
            [
                "iqtree",
                "-s", str(self.aln),
                "-pre", str(self.prefix),
                "-m", self.model, 
                "-T", str(ctx.cpus),
                "--threads-max", str(ctx.cpus),
                "-st", "DNA",
                "-redo"
            ], 
            description="Building phylogenetic tree with IQ-TREE"
        )
        if ctx.ram:
            iqtree_cmd.command.extend(["-mem", f"{ctx.ram}G"])
        if self.fconst:
            iqtree_cmd.command.extend(["-fconst", self.fconst])
        if self.fast_mode:
            iqtree_cmd.command.append("--fast")
        else:
            # Ultrafast bootstrap (-bb) does not work with -fast option
            iqtree_cmd.command.extend(["-bb", str(self.bootstrap)])
        return [validate_aln_cmd, iqtree_cmd]

    def check_aln_has_three_samples(self):
        with open(self.aln) as f:
            num_samples = 0
            for line in f:
                if num_samples >= 3:
                    break
                if line.startswith(">"):
                    num_samples += 1
        if num_samples < 3:
            raise TreeBuildingError(f"Alignment must contain at least 3 samples to build a tree, but found only {num_samples} in {self.aln}") 


class ScaleTreeToSNPs(BaseStage):
    """Scale Newick branch lengths from substitutions per site to expected SNP counts."""

    tree: Path = Field(..., description="Input tree with branch lengths in substitutions per site")
    aln: Path = Field(..., description="Original alignment used to build the tree")
    fconst: Optional[str] = Field(default=None, description="Constant patterns added to the alignment for IQ-TREE")

    _dependencies = [biopython]

    @property
    def output(self) -> ScaleTreeToSNPsOutput:
        return ScaleTreeToSNPsOutput(tree=Path(f"{self.prefix}.snps.newick"))

    def create_commands(self, ctx):
        return [
            self.python_cmd(
                func=self.scale_tree_to_snps,
                args=[self.tree, self.aln, self.output.tree, self.fconst],
                description="Scale tree branch lengths to expected SNP counts",
            )
        ]

    @staticmethod
    def count_constant_sites(fconst: Optional[str]) -> int:
        if not fconst:
            return 0

        fconst_value = str(fconst).strip()

        try:
            return sum(int(count.strip()) for count in fconst_value.split(","))
        except ValueError as exc:
            raise TreeBuildingError(
                f"Invalid constant site counts for fconst: {fconst}"
            ) from exc

    @classmethod
    def count_alignment_sites(cls, aln: Path, fconst: Optional[str] = None) -> int:
        expected_length = None
        sequence_count = 0
        for record in SeqIO.parse(str(aln), "fasta"):
            sequence_count += 1
            sequence_length = len(record.seq)
            if expected_length is None:
                expected_length = sequence_length
            elif sequence_length != expected_length:
                raise TreeBuildingError(
                    f"Alignment sequences must all have the same length in {aln}: "
                    f"expected {expected_length}, found {sequence_length} for {record.id}"
                )

        if sequence_count == 0 or expected_length is None:
            raise TreeBuildingError(f"No sequences found in alignment: {aln}")

        return expected_length + cls.count_constant_sites(fconst)

    @classmethod
    def scale_tree_to_snps(
        cls,
        tree: Path,
        aln: Path,
        output_tree: Path,
        fconst: Optional[str] = None,
    ) -> None:
        alignment_sites = cls.count_alignment_sites(aln, fconst)
        scaled_tree = Phylo.read(str(tree), "newick")

        for clade in scaled_tree.find_clades():
            if clade.branch_length is not None:
                clade.branch_length *= alignment_sites

        with output_tree.open("w") as handle:
            Phylo.write(
                scaled_tree,
                handle,
                "newick",
                format_branch_length=NEWICK_BRANCH_LENGTH_FORMAT,
            )
