name: Test and coverage

on:
  pull_request:               # and every PR targeting main
    branches: [main]

permissions:
  contents: write

jobs:

  test-and-coverage:
    uses: ./.github/workflows/tests.yaml
    permissions:               # 👈 grant the scopes downstream
      contents: write
      pull-requests: write
    secrets: inherit                     # pass all secrets down

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml

  benchmark:
    uses: ./.github/workflows/benchmark.yaml
    secrets: inherit
