name: Test and coverage

on:
  pull_request:               # and every PR targeting main
    branches: [main]

permissions:
  contents: write

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set-up pixi environment
        uses: prefix-dev/setup-pixi@v0.8.3

      - name: Install Hatch
        run: pip install hatch

      - name: Run tests with coverage
        run: |
          hatch run cov
      
      - name: Fail if coverage decreased
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./coverage.xml
          diff: true
          diff-branch: main
          coverage-reduction-failure: true   # 🔴 makes the job fail
          fail: true                         # same, explicit
