name: Test and coverage

on:
  pull_request:               # and every PR targeting main
    branches: [main]

permissions:
  contents: write

jobs:

  test-and-coverage:
    uses: ./.github/workflows/tests.yml 
    secrets: inherit                     # pass all secrets down

  benchmark:
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
